# Generated by Django 4.0.4 on 2022-04-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('description', models.TextField(max_length=400)),
                ('d_type', models.CharField(default='', max_length=30)),
                ('frequency', models.CharField(default='', max_length=10)),
                ('discriminator', models.BooleanField(default=False)),
                ('ground_balance', models.CharField(default='', max_length=25)),
                ('sencetivity_settings', models.BooleanField(default=False)),
                ('headphone', models.BooleanField(default=False)),
                ('headphone_type', models.CharField(default='', max_length=30)),
                ('coil_diameter', models.CharField(blank=True, default='', max_length=10)),
                ('waterproof_coil', models.BooleanField(default=False)),
                ('length', models.CharField(default='', max_length=30)),
                ('work_pattern', models.CharField(default='', max_length=30)),
                ('is_offer', models.BooleanField(default='')),
                ('price', models.IntegerField(default=100)),
                ('brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.brand')),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.material')),
                ('producing_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.country')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Pictures/')),
                ('is_preview', models.BooleanField(default=False)),
                ('product_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default=None, max_length=25)),
                ('text', models.TextField(blank=True, max_length=400)),
                ('pub_date', models.DateField(auto_now=True)),
                ('product_inst', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('distributors', models.ManyToManyField(blank=True, to='shop.distributor')),
            ],
        ),
    ]
