# Generated by Django 2.2.12 on 2022-03-10 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_comment_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default=None, upload_to='Pictures/'),
        ),
    ]
