# Generated by Django 4.0.4 on 2022-04-15 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_work_pattern'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='coil_diameter',
            field=models.IntegerField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='frequency',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='ground_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='waterproof_coil',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='d_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.detectortype'),
        ),
    ]
